[package]
name = "viewports"
version = "0.1.0"
authors = ["konkitoman"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false

[features]
wgpu = ["eframe/wgpu"]

[dependencies]
eframe = { path = "../../crates/eframe" }
env_logger = "0.10"
